# Generated by Django 5.2 on 2025-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_reminder_text_reminder_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
